# Generated by Django 4.0.4 on 2022-06-11 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Cтатусы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='описание задачи')),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('endtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время завершения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category', verbose_name='категория задачи')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.status', verbose_name='текущий статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
