# Generated by Django 4.0.4 on 2022-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-id'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Cтатусы'},
        ),
        migrations.AlterField(
            model_name='task',
            name='endtime',
            field=models.DateTimeField(auto_now=True, verbose_name='время завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.DateTimeField(auto_now=True, verbose_name='время создания'),
        ),
    ]
