# Generated by Django 4.0.4 on 2022-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endtime',
            field=models.DateTimeField(verbose_name='время завершения'),
        ),
    ]
