# Generated by Django 4.0.4 on 2022-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время завершения'),
        ),
    ]
