# Generated by Django 4.0.4 on 2022-06-16 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания'),
        ),
    ]
